[package]
name = "geometrize"
authors = ["Bart Massey <bart@cs.pdx.edu>"]
version = "0.1.1"
edition = "2021"
license-file = "LICENSE.txt"

[dependencies]
argwerk = "0.20"
image = "0.23"
ordered-float = "2"

[[bin]]
name = "geometrize"
path = "geometrize.rs"
