[package]
name = "geometrize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argwerk = "0.20.0"
image = "0.23.14"
ordered-float = "2.10.0"

[[bin]]
name = "geometrize"
path = "geometrize.rs"
